[project]
name = "game-of-life"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.1",
    "pygame>=2.6.1",
    "pytest>=9.0.2",
]

[tool.uv]
package = true
